In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import missingno as msno

sns.set(style='darkgrid')
import matplotlib.pyplot as plt

import joblib
import os

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

---

In [6]:
client_1_data = pd.read_csv("Sisira Horizontal/trial new/Horizontally splitted data/client_1_data.csv")
client_1_data.shape

(504159, 36)

In [7]:
client_2_data = pd.read_csv("Sisira Horizontal/trial new/Horizontally splitted data/client_2_data.csv")
client_2_data.shape

(504159, 36)

In [8]:
client_3_data = pd.read_csv("Sisira Horizontal/trial new/Horizontally splitted data/client_3_data.csv")
client_3_data.shape

(504159, 36)

In [9]:
client_4_data = pd.read_csv("Sisira Horizontal/trial new/Horizontally splitted data/client_4_data.csv")
client_4_data.shape

(504159, 36)

In [10]:
client_5_data = pd.read_csv("Sisira Horizontal/trial new/Horizontally splitted data/client_5_data.csv")
client_5_data.shape

(504159, 36)

---

In [5]:
base_path="Sisira /trial new/Fresh_models"

In [6]:
# Load Client 1's horizontally split data
client1_data = pd.read_csv("Sisira /trial new/client_1_data.csv")  # Update the file path for Client 1's dataset

# Separate features and target
X = client1_data.drop(columns=["Attack Type"])  # All columns except 'Attack Type' (features)
y = client1_data["Attack Type"]  # 'Attack Type' is the target

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Random Forest Classifier
rf_model_client1 = RandomForestClassifier(random_state=42)

# Train the model
rf_model_client1.fit(X_train, y_train)

# Save the trained model as a .pkl file
model_filename = "client_1_model.pkl"
joblib.dump(rf_model_client1, f"{base_path}/{model_filename}")
print(f"Trained model for Client 1 saved as '{model_filename}'")

# Predict on test set
y_pred_client1 = rf_model_client1.predict(X_test)

# Evaluate the model
accuracy_client1 = accuracy_score(y_test, y_pred_client1)
precision_client1 = precision_score(y_test, y_pred_client1, average="weighted")
recall_client1 = recall_score(y_test, y_pred_client1, average="weighted")
f1_client1 = f1_score(y_test, y_pred_client1, average="weighted")

# Confusion Matrix
conf_matrix_client1 = confusion_matrix(y_test, y_pred_client1)

# Extracting True Positives, False Positives, True Negatives, and False Negatives
TP_client1 = conf_matrix_client1.diagonal().sum()  # True Positives (Sum of diagonal values)
FP_client1 = conf_matrix_client1.sum(axis=0) - conf_matrix_client1.diagonal()  # False Positives
FN_client1 = conf_matrix_client1.sum(axis=1) - conf_matrix_client1.diagonal()  # False Negatives
TN_client1 = conf_matrix_client1.sum() - (FP_client1 + FN_client1 + TP_client1)  # True Negatives

# Print metrics
print("Confusion Matrix for Client 1:\n", conf_matrix_client1)
print(f"Accuracy for Client 1: {accuracy_client1 * 100:.2f}%")
print(f"Precision for Client 1: {precision_client1:.2f}")
print(f"Recall for Client 1: {recall_client1:.2f}")
print(f"F1 Score for Client 1: {f1_client1:.2f}")

print("\nDetailed Classification Report for Client 1:\n", classification_report(y_test, y_pred_client1))

print("\nTrue Positives for Client 1:", TP_client1)
print("False Positives for Client 1:", FP_client1.sum())
print("True Negatives for Client 1:", TN_client1.sum())
print("False Negatives for Client 1:", FN_client1.sum())


Trained model for Client 1 saved as 'client_1_model.pkl'


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Client 1:
 [[83728     9     1     3    16     0    43     0]
 [   40    33     0     0     0     0     0     0]
 [    5     0   377     0     0     0     0     1]
 [    1     0     0  5146     3     0     0     0]
 [   41     0     0     0  7595     0     0     0]
 [    1     0     0     0     0     0     0     0]
 [   25     0     0     0     4     0  3666     0]
 [    6     0     3     0     0     0     0    85]]
Accuracy for Client 1: 99.80%
Precision for Client 1: 1.00
Recall for Client 1: 1.00
F1 Score for Client 1: 1.00


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Detailed Classification Report for Client 1:
               precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     83800
         Bot       0.79      0.45      0.57        73
 Brute Force       0.99      0.98      0.99       383
        DDoS       1.00      1.00      1.00      5150
         DoS       1.00      0.99      1.00      7636
Infiltration       0.00      0.00      0.00         1
   Port Scan       0.99      0.99      0.99      3695
  Web Attack       0.99      0.90      0.94        94

    accuracy                           1.00    100832
   macro avg       0.84      0.79      0.81    100832
weighted avg       1.00      1.00      1.00    100832


True Positives for Client 1: 100630
False Positives for Client 1: 202
True Negatives for Client 1: 1212
False Negatives for Client 1: 202


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [7]:
# Load Client 2's horizontally split data
client2_data = pd.read_csv("Sisira /trial new/client_2_data.csv")  # Update the file path for Client 2's dataset

# Separate features and target
X = client2_data.drop(columns=["Attack Type"])  # All columns except 'Attack Type' (features)
y = client2_data["Attack Type"]  # 'Attack Type' is the target

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Random Forest Classifier
rf_model_client2 = RandomForestClassifier(random_state=42)

# Train the model
rf_model_client2.fit(X_train, y_train)

# Save the trained model as a .pkl file
model_filename = "client_2_model.pkl"
joblib.dump(rf_model_client2, f"{base_path}/{model_filename}")
print(f"Trained model for Client 2 saved as '{model_filename}'")

# Predict on test set
y_pred_client2 = rf_model_client2.predict(X_test)

# Evaluate the model
accuracy_client2 = accuracy_score(y_test, y_pred_client2)
precision_client2 = precision_score(y_test, y_pred_client2, average="weighted")
recall_client2 = recall_score(y_test, y_pred_client2, average="weighted")
f1_client2 = f1_score(y_test, y_pred_client2, average="weighted")

# Confusion Matrix
conf_matrix_client2 = confusion_matrix(y_test, y_pred_client2)

# Extract True Positives, False Positives, True Negatives, and False Negatives
TP_client2 = conf_matrix_client2.diagonal().sum()
FP_client2 = conf_matrix_client2.sum(axis=0) - conf_matrix_client2.diagonal()
FN_client2 = conf_matrix_client2.sum(axis=1) - conf_matrix_client2.diagonal()
TN_client2 = conf_matrix_client2.sum() - (FP_client2 + FN_client2 + TP_client2)

# Print metrics
print("Confusion Matrix for Client 2:\n", conf_matrix_client2)
print(f"Accuracy for Client 2: {accuracy_client2 * 100:.2f}%")
print(f"Precision for Client 2: {precision_client2:.2f}")
print(f"Recall for Client 2: {recall_client2:.2f}")
print(f"F1 Score for Client 2: {f1_client2:.2f}")

print("\nDetailed Classification Report for Client 2:\n", classification_report(y_test, y_pred_client2))

print("\nTrue Positives for Client 2:", TP_client2)
print("False Positives for Client 2:", FP_client2.sum())
print("True Negatives for Client 2:", TN_client2.sum())
print("False Negatives for Client 2:", FN_client2.sum())


Trained model for Client 2 saved as 'client_2_model.pkl'


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Client 2:
 [[83976     8     1     0    12     0    50     0]
 [   43    35     0     0     0     0     0     0]
 [    5     0   364     0     1     0     0     1]
 [    5     0     0  5117     0     0     0     0]
 [   48     0     0     1  7522     0     0     0]
 [    2     0     0     0     0     0     0     0]
 [   23     0     0     0     2     0  3533     0]
 [    4     0     0     0     1     0     0    78]]
Accuracy for Client 2: 99.79%
Precision for Client 2: 1.00
Recall for Client 2: 1.00
F1 Score for Client 2: 1.00


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Detailed Classification Report for Client 2:
               precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     84047
         Bot       0.81      0.45      0.58        78
 Brute Force       1.00      0.98      0.99       371
        DDoS       1.00      1.00      1.00      5122
         DoS       1.00      0.99      1.00      7571
Infiltration       0.00      0.00      0.00         2
   Port Scan       0.99      0.99      0.99      3558
  Web Attack       0.99      0.94      0.96        83

    accuracy                           1.00    100832
   macro avg       0.85      0.79      0.81    100832
weighted avg       1.00      1.00      1.00    100832


True Positives for Client 2: 100625
False Positives for Client 2: 207
True Negatives for Client 2: 1242
False Negatives for Client 2: 207


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [9]:
client3_data = pd.read_csv("Sisira /trial new/client_3_data.csv")

X = client3_data.drop(columns=["Attack Type"])
y = client3_data["Attack Type"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model_client3 = RandomForestClassifier(random_state=42)
rf_model_client3.fit(X_train, y_train)

model_filename = "client_3_model.pkl"
joblib.dump(rf_model_client3, f"{base_path}/{model_filename}")
print(f"Trained model for Client 3 saved as '{model_filename}'")

y_pred_client3 = rf_model_client3.predict(X_test)

accuracy_client3 = accuracy_score(y_test, y_pred_client3)
precision_client3 = precision_score(y_test, y_pred_client3, average="weighted")
recall_client3 = recall_score(y_test, y_pred_client3, average="weighted")
f1_client3 = f1_score(y_test, y_pred_client3, average="weighted")

conf_matrix_client3 = confusion_matrix(y_test, y_pred_client3)

TP_client3 = conf_matrix_client3.diagonal().sum()
FP_client3 = conf_matrix_client3.sum(axis=0) - conf_matrix_client3.diagonal()
FN_client3 = conf_matrix_client3.sum(axis=1) - conf_matrix_client3.diagonal()
TN_client3 = conf_matrix_client3.sum() - (FP_client3 + FN_client3 + TP_client3)

print("Confusion Matrix for Client 3:\n", conf_matrix_client3)
print(f"Accuracy for Client 3: {accuracy_client3 * 100:.2f}%")
print(f"Precision for Client 3: {precision_client3:.2f}")
print(f"Recall for Client 3: {recall_client3:.2f}")
print(f"F1 Score for Client 3: {f1_client3:.2f}")

print("\nDetailed Classification Report for Client 3:\n", classification_report(y_test, y_pred_client3))

print("\nTrue Positives for Client 3:", TP_client3)
print("False Positives for Client 3:", FP_client3.sum())
print("True Negatives for Client 3:", TN_client3.sum())
print("False Negatives for Client 3:", FN_client3.sum())


Trained model for Client 3 saved as 'client_3_model.pkl'


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Client 3:
 [[83579    19     2     0    13     0     0    54     1]
 [   29    48     0     0     0     0     0     0     0]
 [    6     0   388     0     0     0     0     0     1]
 [    5     0     0  5130     1     0     0     0     0]
 [   45     0     0     0  7774     0     0     0     0]
 [    2     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0]
 [   20     0     0     0     1     0     0  3630     1]
 [    6     0     0     0     0     0     0     0    76]]
Accuracy for Client 3: 99.79%
Precision for Client 3: 1.00
Recall for Client 3: 1.00
F1 Score for Client 3: 1.00


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Detailed Classification Report for Client 3:
               precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     83668
         Bot       0.72      0.62      0.67        77
 Brute Force       0.99      0.98      0.99       395
        DDoS       1.00      1.00      1.00      5136
         DoS       1.00      0.99      1.00      7819
  Heartbleed       0.00      0.00      0.00         2
Infiltration       0.00      0.00      0.00         1
   Port Scan       0.99      0.99      0.99      3652
  Web Attack       0.96      0.93      0.94        82

    accuracy                           1.00    100832
   macro avg       0.74      0.72      0.73    100832
weighted avg       1.00      1.00      1.00    100832


True Positives for Client 3: 100625
False Positives for Client 3: 207
True Negatives for Client 3: 1449
False Negatives for Client 3: 207


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [11]:
client4_data = pd.read_csv("Sisira /trial new/client_4_data.csv")

X = client4_data.drop(columns=["Attack Type"])
y = client4_data["Attack Type"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model_client4 = RandomForestClassifier(random_state=42)
rf_model_client4.fit(X_train, y_train)

model_filename = "client_4_model.pkl"
joblib.dump(rf_model_client4, f"{base_path}/{model_filename}")
print(f"Trained model for Client 4 saved as '{model_filename}'")

y_pred_client4 = rf_model_client4.predict(X_test)

accuracy_client4 = accuracy_score(y_test, y_pred_client4)
precision_client4 = precision_score(y_test, y_pred_client4, average="weighted")
recall_client4 = recall_score(y_test, y_pred_client4, average="weighted")
f1_client4 = f1_score(y_test, y_pred_client4, average="weighted")

conf_matrix_client4 = confusion_matrix(y_test, y_pred_client4)

TP_client4 = conf_matrix_client4.diagonal().sum()
FP_client4 = conf_matrix_client4.sum(axis=0) - conf_matrix_client4.diagonal()
FN_client4 = conf_matrix_client4.sum(axis=1) - conf_matrix_client4.diagonal()
TN_client4 = conf_matrix_client4.sum() - (FP_client4 + FN_client4 + TP_client4)

print("Confusion Matrix for Client 4:\n", conf_matrix_client4)
print(f"Accuracy for Client 4: {accuracy_client4 * 100:.2f}%")
print(f"Precision for Client 4: {precision_client4:.2f}")
print(f"Recall for Client 4: {recall_client4:.2f}")
print(f"F1 Score for Client 4: {f1_client4:.2f}")

print("\nDetailed Classification Report for Client 4:\n", classification_report(y_test, y_pred_client4))

print("\nTrue Positives for Client 4:", TP_client4)
print("False Positives for Client 4:", FP_client4.sum())
print("True Negatives for Client 4:", TN_client4.sum())
print("False Negatives for Client 4:", FN_client4.sum())


Trained model for Client 4 saved as 'client_4_model.pkl'


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Client 4:
 [[83679    11     1     2    21     0     0    55     0]
 [   32    42     0     0     0     0     0     0     0]
 [    9     0   369     0     0     0     0     0     0]
 [    5     0     0  5151     4     0     0     0     0]
 [   50     0     0     2  7781     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0]
 [   24     0     0     0     3     0     0  3494     0]
 [    1     0     2     0     0     0     0     0    92]]
Accuracy for Client 4: 99.78%
Precision for Client 4: 1.00
Recall for Client 4: 1.00
F1 Score for Client 4: 1.00


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Detailed Classification Report for Client 4:
               precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     83769
         Bot       0.79      0.57      0.66        74
 Brute Force       0.99      0.98      0.98       378
        DDoS       1.00      1.00      1.00      5160
         DoS       1.00      0.99      0.99      7833
  Heartbleed       0.00      0.00      0.00         1
Infiltration       0.00      0.00      0.00         1
   Port Scan       0.98      0.99      0.99      3521
  Web Attack       1.00      0.97      0.98        95

    accuracy                           1.00    100832
   macro avg       0.75      0.72      0.73    100832
weighted avg       1.00      1.00      1.00    100832


True Positives for Client 4: 100608
False Positives for Client 4: 224
True Negatives for Client 4: 1568
False Negatives for Client 4: 224


/jupyter/dtids.user01/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [12]:
client5_data = pd.read_csv("Sisira /trial new/client_5_data.csv")

X = client5_data.drop(columns=["Attack Type"])
y = client5_data["Attack Type"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model_client5 = RandomForestClassifier(random_state=42)
rf_model_client5.fit(X_train, y_train)

model_filename = "client_5_model.pkl"
joblib.dump(rf_model_client5, f"{base_path}/{model_filename}")
print(f"Trained model for Client 5 saved as '{model_filename}'")

y_pred_client5 = rf_model_client5.predict(X_test)

accuracy_client5 = accuracy_score(y_test, y_pred_client5)
precision_client5 = precision_score(y_test, y_pred_client5, average="weighted")
recall_client5 = recall_score(y_test, y_pred_client5, average="weighted")
f1_client5 = f1_score(y_test, y_pred_client5, average="weighted")

conf_matrix_client5 = confusion_matrix(y_test, y_pred_client5)

TP_client5 = conf_matrix_client5.diagonal().sum()
FP_client5 = conf_matrix_client5.sum(axis=0) - conf_matrix_client5.diagonal()
FN_client5 = conf_matrix_client5.sum(axis=1) - conf_matrix_client5.diagonal()
TN_client5 = conf_matrix_client5.sum() - (FP_client5 + FN_client5 + TP_client5)

print("Confusion Matrix for Client 5:\n", conf_matrix_client5)
print(f"Accuracy for Client 5: {accuracy_client5 * 100:.2f}%")
print(f"Precision for Client 5: {precision_client5:.2f}")
print(f"Recall for Client 5: {recall_client5:.2f}")
print(f"F1 Score for Client 5: {f1_client5:.2f}")

print("\nDetailed Classification Report for Client 5:\n", classification_report(y_test, y_pred_client5))

print("\nTrue Positives for Client 5:", TP_client5)
print("False Positives for Client 5:", FP_client5.sum())
print("True Negatives for Client 5:", TN_client5.sum())
print("False Negatives for Client 5:", FN_client5.sum())


Trained model for Client 5 saved as 'client_5_model.pkl'
Confusion Matrix for Client 5:
 [[83850     7     1     0    11     0    43     1]
 [   35    36     0     0     0     0     0     0]
 [    6     0   348     0     0     0     0     0]
 [    7     0     0  5123     5     0     0     0]
 [   35     0     0     1  7669     0     0     0]
 [    0     0     0     0     0     1     0     0]
 [   23     0     0     0     1     0  3539     0]
 [    4     0     1     0     1     0     0    84]]
Accuracy for Client 5: 99.82%
Precision for Client 5: 1.00
Recall for Client 5: 1.00
F1 Score for Client 5: 1.00

Detailed Classification Report for Client 5:
               precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     83913
         Bot       0.84      0.51      0.63        71
 Brute Force       0.99      0.98      0.99       354
        DDoS       1.00      1.00      1.00      5135
         DoS       1.00      1.00      1.00      7705
Infiltration     

<br>
<br>
<br>

---